### ISSUE TITLE
关于AOT

### ISSUE THREAD

**Issue by yunClouds** [wpcfan/awesome-tutorials#12]
@wpcfan 你好，
我之前都是用jit的那种模式配置，然后我参考你关于aot的说明，在main.ts中改用：
![image](https://user-images.githubusercontent.com/26613310/29649918-0321a5fe-88ca-11e7-81b8-2b66fd205ed8.png)
但提示 cannot find module  app.module.ngfactory ，请问这个app.module.ngfactory是哪来的呢？还需要怎么配置？
谢谢！

**Comment by wpcfan** [comment]
用 cli 的话，可以不用配置，直接 ng build --aot 即可

fix #12

**Comment by yunClouds** [comment]
这样啊，不过不是很理解：既然用 cli 不用配置，直接 ng build --aot 即可，那您在文中引导过程部分提到的jit和aot两种编译模式不同的配置又有什么区别作用呢，据我的认识里jit模式也是用的cli啊？
可能我理解的不是很好，还请赐教啊 @wpcfan

**Comment by wpcfan** [comment]
AOT 是在生产阶段使用的，AOT 编译会发现更多错误，会删掉很多没有用的类库，缩小体积，提升效率。但编译过程比较慢。JIT 是开发阶段使用的，含有调试信息。但 ng5 之后开发阶段也会利用 aot

**Comment by yunClouds** [comment]
恩，谢谢
