### ISSUE TITLE
请教一下， 按照书上代码敲完第三章代码 ，运行时报错如下，求指教

### ISSUE THREAD

**Issue by Yijiaoooooo** [wpcfan/awesome-tutorials#14]
ERROR in E:/GithubClone/Angular-Demo/angular01/node_modules/angular-in-memory-web-api/http-client-backend.service.d.ts (1,97): Cannot find module '"@"angular/common/http'.

ERROR in E:/GithubClone/Angular-Demo/angular01/node_modules/angular-in-memory-web-api/http-client-in-memory-web-api.module.d.ts (2,41): Cannot find module '"@"angular/common/http'.

Cannot find module 'angular/common/http'.

**Comment by wpcfan** [comment]
你用的是新版 in-memory-web-api 它依赖的是 http client，但这个依赖是 4.3 以后才有的，所以目前来说或者你降级 in-memory-web-api 到代码使用的版本，或者不理会这章，到后面我们使用了 json-server 作为 web api，不存在这个问题
