### ISSUE TITLE
第三章运行报错请教

### ISSUE THREAD

**Issue by tinytinysun** [wpcfan/awesome-tutorials#17]
我按照书上的代码敲进去，但是运行的时候报错，求指导。

`Error
​
columnNumber: 31
​
fileName: "http://localhost:4200/polyfills.bundle.js line 597 > eval"
​
lineNumber: 809
​
message: "Uncaught (in promise): Object: {\"body\":{\"error\":\"Object(...) is not a function\"},\"url\":\"api/todos\",\"headers\":{\"Content-Type\":[\"application/json\"]},\"status\":500,\"statusText\":\"Internal Server Error\"}"
​
promise: Object { __zone_symbol__state: 0, __zone_symbol__value: {…} }
​
rejection: Object { url: "api/todos", status: 500, statusText: "Internal Server Error", … }
​
stack: "resolvePromise@webpack-internal:///./node_modules/zone.js/dist/zone.js:809:31\nresolvePromise@webpack-internal:///./node_modules/zone.js/dist/zone.js:775:17\nscheduleResolveOrReject/<@webpack-internal:///./node_modules/zone.js/dist/zone.js:858:17\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17\nonInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17\nZone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28\ndrainMicroTaskQueue@webpack-internal:///./node_modules/zone.js/dist/zone.js:595:25\nZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:500:21\nZoneTask/this.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:485:28\ntimer@webpack-internal:///./node_modules/zone.js/dist/zone.js:2025:17\n"
​
task: Object { runCount: 0, _state: "notScheduled", type: "microTask", … }
​
zone: Object { _properties: {…}, _parent: {…}, _name: "angular", … }
​
__proto__: Object { … }`

**Comment by AlwynLiu** [comment]
同样的错误

**Comment by wpcfan** [comment]
看上去应该是 API Server 问题，这个无所谓，后面就换成 JSON Server 了，前面这个伪 API 拦截类库已经升级了，所以不好用了
