### ISSUE TITLE
代码没了，链接失效

### ISSUE THREAD

**Issue by xiaoCong2014** [wpcfan/awesome-tutorials#2]
README.md 文件里的 https://github.com/wpcfan/awesome-tutorials/tree/chap02/angular2/ng2-tut
项目里根本就没有 **tree** 这个文件夹
麻烦顺便检查下其他章节的代码的链接是否也失效了

**Comment by wpcfan** [comment]
你直接在浏览器中打开就知道了，或者fork后checkout到对应章节比如chap01即可

**Comment by wpcfan** [comment]
那个链接是用来在浏览器中查看代码的，并没有失效。
