### ISSUE TITLE
项目所用的ng的版本具体是多少?

### ISSUE THREAD

**Issue by xiaoCong2014** [wpcfan/awesome-tutorials#7]
之所以提这个是因为我在本地无法运行项目，应该是版本的问题。
你在 readMe.md 文件里的 "环境配置要求" 部分写了 安装ng的命令，但最好补充下安装的ng的版本，比如在文章补充一下  "npm install -g @angular/cli@latest 命令执行后，安装的版本是 2.4.10"，或者命令里指定ng版本

**Comment by wpcfan** [comment]
其实如果使用 `npm install -g angular-cli@latest` 而不是  `npm install -g @angular/cli@latest` 就可以和课程一样的环境了，因为 Angular CLI 合并到 angular 核心项目后配置文件和 目标的 Angular版本都改变了

**Comment by wpcfan** [comment]
后期会把课程代码升级到4
